version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: sairam2004
      MYSQL_DATABASE: maverick_bank
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - bank-network

  backend:
    build: ./backend
    container_name: backend_container
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - bank-network

  frontend:
    build: ./frontend
    container_name: frontend_container
    ports:
      - "4200:80"
    depends_on:
      - backend
    networks:
      - bank-network

volumes:
  mysql_data:

networks:
  bank-network:
